[package]
name = "to-socket-addrs"
version = "0.1.0"
edition = "2021"
authors = [ "Sergey V. Kokorin <nvksv@nvksv.ru>" ]
description = "A small std::net::ToSocketAddrs replacement to specify addresses without port"
repository = "https://github.com/nvksv/to-socket-addrs/"
homepage = "https://github.com/nvksv/to-socket-addrs/"
documentation = "https://docs.rs/to-socket-addrs/"
readme = "README.md"
license = "MIT"
keywords = ["tosocketaddrs", "socketaddr"]
categories = [ "network-programming" ]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md",
]

[dependencies]
